import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {ArrowLeft,Check,ChevronRight,Clock3,Crosshair,Heart,LockKeyhole,Map,Music,RotateCcw,Shield,Skull,Volume2,VolumeX,X,Zap} from 'lucide-react';
import {clothes,past,pronouns,type Q} from './data';
type Screen='home'|'map'|'game'|'result'|'victory'; type Game='past'|'pronouns'|'clothes';
const meta={past:{place:'SCHOOL DISTRICT',title:'Оборона баррикады',topic:'PAST SIMPLE',goal:7},pronouns:{place:'DOWNTOWN',title:'Зомби-ловушка',topic:'PRONOUNS',goal:9},clothes:{place:'SHOPPING MALL',title:'Назови и уничтожь',topic:'CLOTHES',goal:8}} as const;
const shuffle=<T,>(a:T[])=>[...a].sort(()=>Math.random()-.5);
export function App(){
 const [screen,setScreen]=useState<Screen>('home'); const [game,setGame]=useState<Game>('past');
 const [cleared,setCleared]=useState<Game[]>(()=>JSON.parse(localStorage.getItem('ze-cleared')||'[]'));
 const [score,setScore]=useState(0); const [muted,setMuted]=useState(()=>localStorage.getItem('ze-muted')==='1');
 const [result,setResult]=useState({correct:0,total:10,won:false,score:0});
 const audio=useRef<AudioContext|null>(null);
 const sfx=useCallback((ok=true)=>{if(muted)return; const C=window.AudioContext||window.webkitAudioContext; audio.current??=new C(); const ctx=audio.current,o=ctx.createOscillator(),g=ctx.createGain();o.type=ok?'square':'sawtooth';o.frequency.setValueAtTime(ok?280:120,ctx.currentTime);o.frequency.exponentialRampToValueAtTime(ok?620:70,ctx.currentTime+.14);g.gain.setValueAtTime(.06,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.16);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+.17)},[muted]);
 const toggle=()=>{setMuted(v=>{localStorage.setItem('ze-muted',v?'0':'1');return !v})};
 const start=(g:Game)=>{setGame(g);setScreen('game')};
 const finish=(correct:number,total:number,points:number)=>{const won=correct>=meta[game].goal;setScore(s=>s+points);setResult({correct,total,won,score:points});if(won&&!cleared.includes(game)){const n=[...cleared,game];setCleared(n);localStorage.setItem('ze-cleared',JSON.stringify(n));}setScreen(won&&cleared.length===2?'victory':'result')};
 return <main className={`app screen-${screen}`}>
  {screen==='home'&&<Home onStart={()=>setScreen('map')} muted={muted} toggle={toggle}/>} 
  {screen==='map'&&<CityMap cleared={cleared} score={score} start={start} home={()=>setScreen('home')} muted={muted} toggle={toggle}/>} 
  {screen==='game'&&<GameScreen key={game+Date.now()} game={game} finish={finish} back={()=>setScreen('map')} sfx={sfx} muted={muted} toggle={toggle}/>} 
  {screen==='result'&&<Result result={result} game={game} replay={()=>start(game)} map={()=>setScreen('map')}/>} 
  {screen==='victory'&&<Victory score={score+result.score} reset={()=>{localStorage.removeItem('ze-cleared');setCleared([]);setScore(0);setScreen('home')}}/>}
 </main>
}
declare global{interface Window{webkitAudioContext:typeof AudioContext}}
function Sound({muted,toggle}:{muted:boolean;toggle:()=>void}){return <button className="icon-btn" onClick={toggle} aria-label={muted?'Включить звук':'Выключить звук'}>{muted?<VolumeX/>:<Volume2/>}</button>}
function Home({onStart,muted,toggle}:{onStart:()=>void;muted:boolean;toggle:()=>void}){return <section className="hero"><header className="top"><div className="brand"><Skull/> ZE // OUTBREAK</div><Sound muted={muted} toggle={toggle}/></header><div className="hero-copy"><p className="eyebrow"><span/> ENGLISH SURVIVAL PROGRAM // A1–A2</p><h1>ZOMBIE<br/><em>ENGLISH</em></h1><p className="lead">Учи английский. Побеждай заражённых.<br/>Освободи город район за районом.</p><button className="primary huge" onClick={onStart}>СПАСТИ ГОРОД <ChevronRight/></button><div className="mission"><span>03</span><p><b>РАЙОНА ЗАРАЖЕНЫ</b><br/>Только твои знания остановят вспышку.</p></div></div><footer className="hero-foot">СИГНАЛ ОБНАРУЖЕН <i/><span>ПРОГРЕСС СОХРАНЯЕТСЯ АВТОМАТИЧЕСКИ</span></footer></section>}
function CityMap({cleared,score,start,home,muted,toggle}:{cleared:Game[];score:number;start:(g:Game)=>void;home:()=>void;muted:boolean;toggle:()=>void}){return <section className="map-page"><header className="top"><button className="back" onClick={home}><ArrowLeft/> ГЛАВНАЯ</button><div className="brand"><Skull/> ZOMBIE ENGLISH</div><div className="top-actions"><span>ОЧКИ <b>{score.toString().padStart(4,'0')}</b></span><Sound muted={muted} toggle={toggle}/></div></header><div className="map-head"><div><p className="eyebrow"><span/> ОПЕРАЦИЯ: ЧИСТЫЙ ГОРОД</p><h2>КАРТА <em>ЗАРАЖЕНИЯ</em></h2></div><p>Выбери район и выполни учебную миссию.<br/>Очисти все три зоны, чтобы спасти город.</p></div><div className="districts">{(['past','pronouns','clothes'] as Game[]).map((g,i)=><article key={g} className={`district d${i+1} ${cleared.includes(g)?'clean':''}`}><div className="district-art"><span className="number">0{i+1}</span><span className="status">{cleared.includes(g)?<><Check/> ОЧИЩЕН</>:<>ЗАРАЖЁН</>}</span><div className="pin">{i===0?<Shield/>:i===1?<Zap/>:<Crosshair/>}</div></div><div className="district-info"><small>{meta[g].place}</small><h3>{meta[g].title}</h3><div className="topic"><span>{meta[g].topic}</span><span>{g==='pronouns'?'12 ЗАДАНИЙ':'10 ЗАДАНИЙ'}</span></div><p>{g==='past'?'Построй оборону с помощью правильных форм глаголов.':g==='pronouns'?'Лови заражённых, выбирая верное местоимение.':'Назови предмет одежды до того, как зомби подойдёт.'}</p><button onClick={()=>start(g)}>{cleared.includes(g)?'СЫГРАТЬ СНОВА':'НАЧАТЬ МИССИЮ'} <ChevronRight/></button></div></article>)}</div><div className="campaign"><b>ПРОГРЕСС КАМПАНИИ</b><div className="bar"><i style={{width:`${cleared.length/3*100}%`}}/></div><strong>{cleared.length} / 3 РАЙОНА ОЧИЩЕНО</strong></div></section>}
function GameScreen({game,finish,back,sfx,muted,toggle}:{game:Game;finish:(c:number,t:number,p:number)=>void;back:()=>void;sfx:(ok?:boolean)=>void;muted:boolean;toggle:()=>void}){
 const total=game==='pronouns'?12:10; const source=game==='past'?past:pronouns; const qs=useMemo(()=>shuffle(source).slice(0,total),[game]); const items=useMemo(()=>shuffle(clothes).slice(0,10),[]);
 const [idx,setIdx]=useState(0),[correct,setCorrect]=useState(0),[streak,setStreak]=useState(0),[feedback,setFeedback]=useState<{ok:boolean;text:string}|null>(null),[lives,setLives]=useState(3),[time,setTime]=useState(60),[typed,setTyped]=useState(''),[hard,setHard]=useState(false);
 const current=qs[idx]; const cloth=items[idx]; const done=()=>finish(correct,total,correct*100+Math.max(0,streak-2)*25);
 useEffect(()=>{if(game!=='pronouns'||feedback)return;const t=setInterval(()=>setTime(v=>{if(v<=1){clearInterval(t);setTimeout(done,0);return 0}return v-1}),1000);return()=>clearInterval(t)},[game,feedback]);
 const answer=(value:string)=>{if(feedback)return;const expected=game==='clothes'?cloth.word:current.answer;const ok=value.trim().toLowerCase()===expected.toLowerCase();const nextCorrect=correct+(ok?1:0);sfx(ok);if(ok){setCorrect(v=>v+1);setStreak(v=>v+1);setFeedback({ok:true,text:'ТОЧНО В ЦЕЛЬ!'})}else{setStreak(0);if(game==='past')setLives(v=>Math.max(0,v-1));if(game==='pronouns')setTime(v=>Math.max(0,v-5));setFeedback({ok:false,text:game==='clothes'?`Подсказка: ${expected[0]}… — ${cloth.ru}`:current.tip})}if(game==='past')setTimeout(()=>{if(idx+1>=total)finish(nextCorrect,total,nextCorrect*100+Math.max(0,streak-2)*25);else{setIdx(v=>v+1);setFeedback(null)}},650)}
 const next=()=>{if(idx+1>=total){done();return}setIdx(v=>v+1);setFeedback(null);setTyped('')};
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((game==='pronouns'||game==='past')&&['1','2','3','4'].includes(e.key)&&current.options[+e.key-1])answer(current.options[+e.key-1])};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)});
 return <section className={`game-page game-${game}`}><header className="game-top"><button className="back" onClick={back}><ArrowLeft/> КАРТА</button><div className="mission-title"><small>МИССИЯ 0{game==='past'?1:game==='pronouns'?2:3}</small><b>{meta[game].place} // {meta[game].topic}</b></div><div className="hud"><span>ОЧКИ <b>{correct*100}</b></span>{game==='past'?<span className="lives">{[0,1,2].map(x=><Heart key={x} fill={x<lives?'currentColor':'none'}/>)}</span>:game==='pronouns'?<span><Clock3/> <b>00:{String(time).padStart(2,'0')}</b></span>:null}<Sound muted={muted} toggle={toggle}/></div></header><div className="game-layout"><div className="scene"><div className="fog"/>{game==='past'?<div className="zombie-answers" aria-label="Варианты ответов на зомби">{current.options.map((option,i)=><button className={`answer-zombie ${feedback&&option===current.answer?'correct-target':''}`} key={option} disabled={!!feedback} onClick={()=>answer(option)} aria-label={`Вариант ${i+1}: ${option}`}><span className="z-option"><kbd>{i+1}</kbd>{option}</span><span className="mini-z-head"><i/><i/></span><span className="mini-z-body"/></button>)}</div>:<div className={`zombie ${feedback?.ok?'hit':''}`}><div className="z-head"><i/><i/></div><div className="z-body"><span/><span/></div></div>}<div className={game==='pronouns'?'trap':'barricade'}>{game==='pronouns'?<Zap/>:<Shield/>}</div><div className="scene-label"><Crosshair/><b>{game==='pronouns'?'ЦЕЛЬ В ЗОНЕ ЛОВУШКИ':game==='past'?'ВЫБЕРИ НУЖНОГО ЗОМБИ':'ЦЕЛЬ ПРИБЛИЖАЕТСЯ'}</b><span>{feedback?.ok?'УГРОЗА УСТРАНЕНА':`${Math.max(4,18-idx)} МЕТРОВ`}</span></div></div><div className="question-panel"><div className="progress-line"><span>ЗАДАНИЕ {idx+1} / {total}</span><i><b style={{width:`${idx/total*100}%`}}/></i>{streak>=2&&<strong>СЕРИЯ ×{streak}</strong>}</div>{game==='clothes'?<ClothesQuestion cloth={cloth} hard={hard} setHard={setHard} typed={typed} setTyped={setTyped} answer={answer}/>:<><small className="rule">{game==='past'?'НАЖМИ НА ЗОМБИ С ПРАВИЛЬНЫМ ОТВЕТОМ':'ВЫБЕРИ ПРАВИЛЬНЫЙ ВАРИАНТ'}</small><h2>{current.prompt}</h2>{game!=='past'&&<div className="answers">{current.options.map((o,i)=><button key={o} disabled={!!feedback} onClick={()=>answer(o)}><kbd>{i+1}</kbd>{o}</button>)}</div>}</>}{feedback&&<div className={`feedback ${feedback.ok?'ok':'bad'} ${game==='past'?'auto-feedback':''}`}><div>{feedback.ok?<Check/>:<X/>}</div><p><b>{feedback.text}</b>{!feedback.ok&&game!=='clothes'&&<span>Правильный ответ: <strong>{current.answer}</strong></span>}</p>{game!=='past'&&<button onClick={next}>{idx+1>=total?'РЕЗУЛЬТАТ':'ДАЛЬШЕ'} <ChevronRight/></button>}</div>}<p className="keyhint"><kbd>1</kbd>–<kbd>4</kbd> выбрать ответ <span>•</span> район: {meta[game].place}</p></div></div></section>
}
function ClothesQuestion({cloth,hard,setHard,typed,setTyped,answer}:{cloth:{word:string;ru:string;icon:string};hard:boolean;setHard:(v:boolean)=>void;typed:string;setTyped:(v:string)=>void;answer:(v:string)=>void}){const opts=useMemo(()=>shuffle([cloth.word,...shuffle(clothes.filter(x=>x.word!==cloth.word)).slice(0,3).map(x=>x.word)]),[cloth]);return <><div className="difficulty"><button className={!hard?'active':''} onClick={()=>setHard(false)}>ВЫБОР</button><button className={hard?'active':''} onClick={()=>setHard(true)}>ВВОД</button></div><small className="rule">WHAT IS THIS?</small><div className={`clothing ${cloth.icon}`}><div className="hanger"/><b>?</b></div>{hard?<form onSubmit={e=>{e.preventDefault();answer(typed)}} className="type-form"><input autoFocus value={typed} onChange={e=>setTyped(e.target.value)} placeholder="Type the word…"/><button>ОТВЕТИТЬ</button></form>:<div className="answers compact">{opts.map((o,i)=><button key={o} onClick={()=>answer(o)}><kbd>{i+1}</kbd>{o}</button>)}</div>}</>}
function Result({result,game,replay,map}:{result:{correct:number;total:number;won:boolean;score:number};game:Game;replay:()=>void;map:()=>void}){return <section className="modal-page"><div className={`result-badge ${result.won?'win':'lose'}`}>{result.won?<Shield/>:<Skull/>}</div><p className="eyebrow"><span/> МИССИЯ ЗАВЕРШЕНА</p><h2>{result.won?'РАЙОН ОЧИЩЕН':'НУЖНО ПОДКРЕПЛЕНИЕ'}</h2><p>{result.won?meta[game].place+' снова под нашим контролем.':`Нужно ${meta[game].goal} правильных ответов. Попробуй ещё раз!`}</p><div className="stats"><div><b>{result.correct}/{result.total}</b><span>ПРАВИЛЬНО</span></div><div><b>{Math.round(result.correct/result.total*100)}%</b><span>ТОЧНОСТЬ</span></div><div><b>+{result.score}</b><span>ОЧКИ</span></div></div><div className="result-actions"><button className="primary" onClick={map}><Map/> НА КАРТУ</button><button onClick={replay}><RotateCcw/> СЫГРАТЬ ЕЩЁ</button></div></section>}
function Victory({score,reset}:{score:number;reset:()=>void}){return <section className="victory"><div><p className="eyebrow"><span/> ОПЕРАЦИЯ ЗАВЕРШЕНА</p><h1>ГОРОД<br/><em>СПАСЁН</em></h1><p>Три района очищены. Английский оказался сильнее эпидемии.</p><div className="victory-score"><span>ИТОГОВЫЙ СЧЁТ</span><b>{score}</b></div><button className="primary huge" onClick={reset}>НОВАЯ КАМПАНИЯ <ChevronRight/></button></div></section>}
